name: GitGuardian

on:
  push:
    branches:
      - main
    paths:
      - "main.py"
      - ".github/workflows/gitguardian.yml"
  pull_request:
    branches:
      - main
    paths:
      - "main.py"
      - ".github/workflows/gitguardian.yml"
  schedule:
    - cron: "0 10 * * 6"
  workflow_dispatch:

jobs:
  scanning:
    name: Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # v4
        with:
          fetch-depth: 0

      - name: GitGuardian scan
        uses: GitGuardian/ggshield-action@master
        env:
          GITHUB_PUSH_BEFORE_SHA: ${{ github.event.before }}
          GITHUB_PUSH_BASE_SHA: ${{ github.event.base }}
          GITHUB_PULL_BASE_SHA: ${{ github.event.pull_request.base.sha }}
          GITHUB_DEFAULT_BRANCH: ${{ github.event.repository.default_branch }}
          GITGUARDIAN_API_KEY: ${{ secrets.GITGUARDIAN_API_KEY }}