name: Synchronize

on:
  push:
    branches:
      - main

jobs:
  init:
    name: 🚩 Initialize
    runs-on: ubuntu-latest
    steps:
      - name: Cancel previous workflow
        uses: styfle/cancel-workflow-action@0.12.1
        with:
          access_token: ${{ github.token }}

  sync:
    name: ♻️ Synchronize
    runs-on: ubuntu-latest
    needs: init
    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
        with:
          fetch-depth: 0

      - name: Synchronize
        uses: hatamiarash7/repo-sync@v0.1.3
        with:
          url: https://gitlab.com/hatamiarash7/asn-by-country.git
          username: hatamiarash7
          token: ${{ secrets.GITLAB_TOKEN }}
